### ISSUE TITLE
url and find does not work on the 2024 website

### ISSUE THREAD

**Issue by MoritzHauer** [skjerns/Sperrmuell-KA#2]
not well tested fixes:
    akal_php = 'https://web4.karlsruhe.de/service/abfall/akal/akal_2024.php'
...
            url = f"{akal_php}?hausnr={number}&strasse={quote(street.strip())}"
...
            dates = re.findall(r'<br><br>Stra&szlig;ensperrm&uuml;ll: (\d+.\d+.\d+)<br><br>', response)

**Comment by skjerns** [comment]
I'm no longer in KA, feel free to propose a PR :)

**Comment by skjerns** [comment]
ok, i updated it :)
